In [1]:
import pandas as pd
import numpy as np

from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.linear_model import RidgeCV, LassoCV


from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [2]:
tree_data = pd.read_csv('s3://220103263-bucket/csv_files/processed/prepared_tree.csv')
linear_data = pd.read_csv('s3://220103263-bucket/csv_files/processed/prepared_linear.csv')

/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/fsspec/registry.py:286: UserWarning: Your installed version of s3fs is very old and known to cause
severe performance issues, see also https://github.com/dask/dask/issues/10276

To fix, you should specify a lower version bound on s3fs, or
update the current installation.

  warnings.warn(s3_msg)

In [3]:
tree_data

,Price,From,To,is_holiday,avialine,duration,days_until_flight,part_of_day
0,10.131181,0,2,0,1,200,36,1
1,10.069002,0,2,0,1,200,43,1
2,10.069002,0,2,0,1,210,50,2
3,10.069002,0,2,0,1,205,59,1
4,10.195411,0,2,0,1,215,61,0
...,...,...,...,...,...,...,...,...
2109,9.659184,1,3,0,3,100,75,3
2110,9.859901,1,3,0,3,100,75,2
2111,9.659184,1,3,0,3,110,75,3
2112,9.859901,1,3,0,3,110,75,0
2113,9.859901,1,3,0,3,90,75,1

In [4]:
linear_data

,Price,is_holiday,duration,days_until_flight,From_Алматы,From_Астана,From_Шымкент,To_Алматы,To_Астана,To_Атырау,To_Шымкент,avialine_Air Astana,avialine_FlyArystan,avialine_Qazaq Air,avialine_SCAT,part_of_day_вечер,part_of_day_день,part_of_day_ночь,part_of_day_утро
0,10.131181,0,4.193800,-0.122540,1,0,0,0,0,1,0,0,1,0,0,0,1,0,0
1,10.069002,0,4.193800,0.203485,1,0,0,0,0,1,0,0,1,0,0,0,1,0,0
2,10.069002,0,4.658654,0.529510,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0
3,10.069002,0,4.426227,0.948685,1,0,0,0,0,1,0,0,1,0,0,0,1,0,0
4,10.195411,0,4.891081,1.041835,1,0,0,0,0,1,0,0,1,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2109,9.659184,0,-0.454739,1.693885,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1
2110,9.859901,0,-0.454739,1.693885,0,1,0,0,0,0,1,0,0,0,1,0,0,1,0
2111,9.659184,0,0.010115,1.693885,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1
2112,9.859901,0,0.010115,1.693885,0,1,0,0,0,0,1,0,0,0,1,1,0,0,0
2113,9.859901,0,-0.919593,1.693885,0,1,0,0,0,0,1,0,0,0,1,0,1,0,0

In [5]:
x_tree = tree_data.drop(columns=['Price'])
y_tree = tree_data['Price']

x_tree_train, x_tree_test, y_tree_train, y_tree_test = train_test_split(x_tree, y_tree, test_size=0.2, random_state = 52)

In [6]:
dt = DecisionTreeRegressor()

dt.fit(x_tree_train, y_tree_train)
dt_test_pred = dt.predict(x_tree_test)
dt_train_pred = dt.predict(x_tree_train)

print("Mean Squared Error (MSE):", np.expm1(mean_squared_error(y_tree_test, dt_test_pred)))
print("Mean Absolute Error (MAE):", np.expm1(mean_absolute_error(y_tree_test, dt_test_pred)))
print("test R² Score:", r2_score(y_tree_test, dt_test_pred))
print("train R² Score:", r2_score(y_tree_train, dt_train_pred))

Mean Squared Error (MSE): 0.0160332514120445
Mean Absolute Error (MAE): 0.07877701117912814
test R² Score: 0.8870720106220934
train R² Score: 0.9969623431515674

In [7]:
gb = GradientBoostingRegressor()

gb.fit(x_tree_train, y_tree_train)
gb_test_pred = gb.predict(x_tree_test)
gb_train_pred = gb.predict(x_tree_train)

print("Mean Squared Error (MSE):", np.expm1(mean_squared_error(y_tree_test, gb_test_pred)))
print("Mean Absolute Error (MAE):", np.expm1(mean_absolute_error(y_tree_test, gb_test_pred)))
print("test R² Score:", r2_score(y_tree_test, gb_test_pred))
print("train R² Score:", r2_score(y_tree_train, dt_train_pred))

Mean Squared Error (MSE): 0.01503657979851151
Mean Absolute Error (MAE): 0.10319641818991362
test R² Score: 0.8940398125465514
train R² Score: 0.9969623431515674

In [8]:
rf = RandomForestRegressor()

rf.fit(x_tree_train, y_tree_train)
rf_test_pred = rf.predict(x_tree_test)
rf_train_pred = rf.predict(x_tree_train)

print("Mean Squared Error (MSE):", np.expm1(mean_squared_error(y_tree_test, rf_test_pred)))
print("Mean Absolute Error (MAE):", np.expm1(mean_absolute_error(y_tree_test, rf_test_pred)))
print("test R² Score:", r2_score(y_tree_test, rf_test_pred))
print("train R² Score:", r2_score(y_tree_train, rf_train_pred))

Mean Squared Error (MSE): 0.009474136390625033
Mean Absolute Error (MAE): 0.07125160236529544
test R² Score: 0.9330533334224457
train R² Score: 0.989040835444953

In [9]:
x_linear = linear_data.drop(columns=['Price'])
y_linear = linear_data['Price']

x_linear_train, x_linear_test, y_linear_train, y_linear_test = train_test_split(x_linear, y_linear, test_size=0.2, random_state = 52)

In [10]:
lm = LinearRegression()

lm.fit(x_linear_train, y_linear_train)
lm_test_pred = lm.predict(x_linear_test)
lm_train_pred = lm.predict(x_linear_train)

print("Mean Squared Error (MSE):", np.expm1(mean_squared_error(y_linear_test, lm_test_pred)))
print("Mean Absolute Error (MAE):", np.expm1(mean_absolute_error(y_linear_test, lm_test_pred)))
print("test R² Score:", r2_score(y_linear_test, lm_test_pred))
print("train R² Score:", r2_score(y_linear_train, lm_train_pred))

Mean Squared Error (MSE): 0.04436630632786939
Mean Absolute Error (MAE): 0.17493445246613962
test R² Score: 0.691800961370094
train R² Score: 0.6951531242747608

In [11]:
alphas = np.logspace(-4, 4, 100)  # 100 альф от 10^-4 до 10^4
ridge_cv = RidgeCV(alphas=alphas, scoring='neg_mean_squared_error', cv=5)
ridge_cv.fit(x_linear_train, y_linear_train)

print("Лучшая alpha для Ridge:", ridge_cv.alpha_)

# === LassoCV ===
lasso_cv = LassoCV(alphas=alphas, cv=5, max_iter=10000)
lasso_cv.fit(x_linear_train, y_linear_train)

print("Лучшая alpha для Lasso:", lasso_cv.alpha_)

Лучшая alpha для Ridge: 0.359381366380463
Лучшая alpha для Lasso: 9.999999999999999e-05

In [12]:
ridge = Ridge(alpha=0.35)

ridge.fit(x_linear_train, y_linear_train)
ridge_test_pred = ridge.predict(x_linear_test)
ridge_train_pred = ridge.predict(x_linear_train)

print("Mean Squared Error (MSE):", np.expm1(mean_squared_error(y_linear_test, ridge_test_pred)))
print("Mean Absolute Error (MAE):", np.expm1(mean_absolute_error(y_linear_test, ridge_test_pred)))
print("test R² Score:", r2_score(y_linear_test, ridge_test_pred))
print("train R² Score:", r2_score(y_linear_train, ridge_train_pred))

Mean Squared Error (MSE): 0.044346545665077036
Mean Absolute Error (MAE): 0.1750007930080904
test R² Score: 0.6919352970246786
train R² Score: 0.6951423593267022

In [13]:
lasso = Lasso(alpha=0.0001)

lasso.fit(x_linear_train, y_linear_train)
lasso_test_pred = lasso.predict(x_linear_test)
lasso_train_pred = lasso.predict(x_linear_train)

print("Mean Squared Error (MSE):", np.expm1(mean_squared_error(y_linear_test, lasso_test_pred)))
print("Mean Absolute Error (MAE):", np.expm1(mean_absolute_error(y_linear_test, lasso_test_pred)))
print("test R² Score:", r2_score(y_linear_test, lasso_test_pred))
print("train R² Score:", r2_score(y_linear_train, lasso_train_pred))

Mean Squared Error (MSE): 0.04432629591155255
Mean Absolute Error (MAE): 0.17496188514546057
test R² Score: 0.6920729602211309
train R² Score: 0.6951252621036141